movie_app/urls.py
from django.conf.urls.static import static
from django.urls import path
from movie_project import settings
from .import views
app_name = 'movie_app'
urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>/',views.detail,name='detail'),
    path('add/',views.add_movie,name="add"),
    path('update/<int:id>/',views.update,name="update"),
    path('delete/<int:id>/',views.delete,name='delete')
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movie_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movie_app.urls'))
]

movie_app/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField(max_length=300)
    year = models.IntegerField()
    img = models.ImageField(upload_to='gallery')
    def __str__(self):
        return self.name

movie_app/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['name','desc','year','img']

movie_app/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.http import HttpResponse
from .models import Movie
from .forms import MovieForm

# Create your views here.
def index(request):
    movie = Movie.objects.all()
    content = {
        'movie_list': movie
    }
    return render(request, 'index.html', content)


def detail(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    return render(request, 'detail_view.html', {'movie': movie})
def add_movie(request):
    if request.method=="POST":
        name = request.POST.get('name')
        desc = request.POST.get('desc')
        year = request.POST.get('year')
        img = request.FILES['img']
        movie = Movie(name=name,desc=desc,year=year,img=img)
        movie.save()
        print('Data added successfully')
    return render(request,'add.html')

def update(request,id):
    movie = Movie.objects.get(id=id)
    form = MovieForm(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'movie':movie})
def delete(request,id):
    if request.method=='POST':
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

templates/add.html
{% extends 'base.html' %}
{% block body %}
    <br><br>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter movie name">
    <input type="text" name="desc" placeholder="Enter a description">
    <input type="number" name="year" placeholder="Enter year of release">
    <label>Upload picture</label>
    <input type="file" name="img">
    <input type="submit" name="submit">
</form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>
<head>
<style>
ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
  background-color: #333;
}

li {
  float: left;
}

li a {
  display: block;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

li a:hover:not(.active) {
  background-color: #111;
}

.active {
  background-color: #04AA6D;
}
</style>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</head>
<body>
<ul>
  <li><a href="{% url "movie_app:add" %}">Add</a></li>
  <li><a href="#">News</a></li>
  <li><a href="#">Contact</a></li>
  <li style="float:right"><a class="active" href="#">About</a></li>
</ul>
{% block body %}
{% endblock %}
</body>
</html>

templates/delete.html
{% extends 'base.html' %}
{% block body %}
    <form method="post">
        {% csrf_token %}
        Are you sure , you want to delete this movie ?
        <button type="submit" class="btn btn-danger">Delete</button>
    </form>
{% endblock %}

templates/detail_view.html
{% extends 'base.html' %}
{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-5">
                <img src="{{ movie.img.url }}" width="90px" height="200px">
            </div>
            <div class="col-md-6">
                <p> movie id : {{ movie.id }}</p>
                <p>movie name: {{ movie.name }}</p>
                <p>year of release: {{ movie.year }}</p>
                <p>theme: {{ movie.desc }}</p>
                 <a class="btn btn-warning" href="{% url 'movie_app:update' movie.id %}">Update</a>
                <a class="btn btn-danger" href="{% url 'movie_app:delete' movie.id %}">Delete</a>
            </div>
        </div>
    </div>
{% endblock %}

templates/edit.html
{%  extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
<input type="submit">
</form>
 {% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block body %}
<p>Hello</p>
    <div class="container">
        <div class="row">
             {% for i in movie_list %}
            <div class="col-md-3">
               <div class="card" style="width: 18rem;">
                <img class="card-img-top" src="{{ i.img.url }}" alt="Card image cap" width="50px" height="200px">
                  <div class="card-body">
                    <h5 class="card-title">{{ i.name }}</h5>
                    <p class="card-text">{{ i.name }}</p>
                    <a href="{%  url "movie_app:detail" i.id %}" class="btn btn-primary">View More</a>
                  </div>
                 </div>
            </div>
             {% endfor %}
        </div>
    </div>
{% endblock %}